services:
  backend:
    image: ${DOCKER_USERNAME}/backend:latest   # Pull from Docker Hub
    container_name: backend_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "${MONGO_URI}"
      DB_NAME: "itemdb"
      COLLECTION_NAME: "items"
      PORT: "8000"

  frontend:
    image: ${DOCKER_USERNAME}/frontend:latest
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: "http://${VITE_API_BASE_URL}"